// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

///! mock verification! (testing) always returns true
Future<bool> verifyEvent(
        {required String id, required String pubkey, required String sig}) =>
    RustLib.instance.api
        .crateApiSimpleVerifyEvent(id: id, pubkey: pubkey, sig: sig);
